export const TESTS_DESCRIPTIONS_ARE_LOADED = 'TESTS_DESCRIPTIONS_ARE_LOADED';

export const TEST_PREVIEW_INFO_IS_LOADED = 'TEST_PREVIEW_INFO_IS_LOADED';
export const CLEAR_TEST_PREVIEW_INFO = 'CLEAR_TEST_PREVIEW_INFO';

export const TEST_QUESTIONS_ARE_LOADED = 'TEST_QUESTIONS_ARE_LOADED';
export const CLEAR_TEST_QUESTIONS = 'CLEAR_TEST_QUESTIONS';
export const SKIP_THE_QUESTION = 'SKIP_THE_QUESTION';
export const ANSWER_THE_QUESTION = 'ANSWER_THE_QUESTION';

export const CLEAR_TEST_ANSWERS = 'CLEAR_TEST_ANSWERS';
export const TEST_ANSWERS_ARE_CHECKED = 'TEST_ANSWERS_ARE_CHECKED';
export const SET_ANSWER_RESULT = 'SET_ANSWER_RESULT';

export const SET_USERNAME = 'SET_USERNAME';
export const CLEAR_USERNAME = 'CLEAR_USERNAME';

export const START_TEST = 'START_TEST';

export const CLEAR_CURRENT_TEST_INFO = 'CLEAR_CURRENT_TEST_INFO';

export const SET_INITIAL_QUESTION_ID = 'SET_INITIAL_QUESTION_ID';
export const CHANGE_QUESTION_ID = 'CHANGE_QUESTION_ID';
